modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="more_tnt"
version="1.0.0"
displayName="More TNT"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="berne, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.more_tnt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



